<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" />
    <PackageReference Include="SQLitePCLRaw.lib.e_sqlite3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Harness.Contracts\Harness.Contracts.csproj" />
    <ProjectReference Include="..\Harness.Identity\Harness.Identity.csproj" />
  </ItemGroup>

</Project>
